version: '3.1'

services:
  api:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    ports:
      - 3000:3000
    image: api/mozao
    restart: always
    volumes: 
      - ./:/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes: 
      - ./docker/data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080